### ISSUE TITLE
Ubacivanje 3D okruženja (stola) u Webots

### ISSUE THREAD

**Issue by filiparag** [memristor/mep3#9]
## To do
- [x] Osnovno okruženje
  - [x] Pod i zidovi (#8)
  - [x] Tekstura poda (#8)
- [x] Specijalizovani delovi (#101)
  - [x] Razdvajanje dispensera u sredini (#96) 
  - [x] Model diska (#11)
  - [x] Starting areas (#13)
  - [x] Campsite
  - [x] Gallery (#90)
  - [x] Excavation squares (#21)
  - [x] Exhibition hall (#97)
  - [x] Excavation site (#13)
  - [x] Work shed (#16)
  - [x] Dispensers (#17)
  - [x] Pedastal (#16)
  - [x] Fixed beacon supports (#98)
  - [x] Central tracking device (#12)
